services:
  server_rule:
    build: ./Server/
    image: edenchik/arhet:server.2.0.0
    # image: server_rule
    command: python ./server_rule.py
    ports:
      - 30880:30880
    depends_on:
      - nanomq
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      iot:
        aliases:
          - server_rule

  rule_engine:
    build: ./Rule/
    image: edenchik/arhet:engine.2.0.0
    # image: rule_engine
    command: python ./rule_engine.py
    depends_on:
      - server_rule
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      iot:
        aliases:
          - rule_engine

  # Основной мастер PostgreSQL
  postgres-primary:
    image: postgres:17.4-alpine
    container_name: postgres-primary
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "cadri"
    volumes:
      - ./postgres-data-primary:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      bash -c "
      # Включаем репликацию
      echo \"host replication all 0.0.0.0/0 md5\" >> /var/lib/postgresql/data/pg_hba.conf &&
      # Настраиваем параметры репликации
      echo \"wal_level = replica\" >> /var/lib/postgresql/data/postgresql.conf &&
      echo \"max_wal_senders = 10\" >> /var/lib/postgresql/data/postgresql.conf &&
      echo \"wal_keep_size = 64MB\" >> /var/lib/postgresql/data/postgresql.conf &&
      postgres"

  # Реплика PostgreSQL
  postgres-replica1:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "cadri"
    volumes:
      - ./postgres-data-replica1:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - postgres-primary
    command: >
      bash -c "
      until pg_isready -h postgres-primary -U postgres; do sleep 1; done &&
      psql -h postgres-primary -U postgres -c 'SELECT * FROM pg_create_physical_replication_slot(\"replica_slot\");' &&
      pg_basebackup -h postgres-primary -D /var/lib/postgresql/data -U postgres -v -P --wal-method=stream &&
      postgres -c hot_standby=on"
    networks:
      - iot

  # Сервис Citus: координатор
  citus-coordinator:
    image: citusdata/citus:11.0
    container_name: citus-coordinator
    environment:
      POSTGRES_PASSWORD: cadri
    ports:
      - "5434:5432"
    volumes:
      - ./citus-data:/var/lib/postgresql/data
    command: >
      bash -c "
        postgres -c shared_preload_libraries='citus' &&
        psql -U postgres -c 'CREATE EXTENSION IF NOT EXISTS citus;'"
    restart: always
    networks:
      - iot

  # Воркер Citus
  citus-worker1:
    image: citusdata/citus:11.0
    environment:
      POSTGRES_PASSWORD: cadri
    ports:
      - "5435:5432"
    volumes:
      - ./citus-worker1-data:/var/lib/postgresql/data
    command: >
      bash -c "
        postgres -c shared_preload_libraries='citus' &&
        psql -U postgres -c 'CREATE EXTENSION IF NOT EXISTS citus;'"
    networks:
      - iot

  pgadmin:
    image: dpage/pgadmin4:9.1
    environment:
      PGADMIN_DEFAULT_EMAIL: "ermo30@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "cadri"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - postgres-primary
    restart: unless-stopped
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      iot:
        aliases:
          - pgadmin

  nanomq:
    image: emqx/nanomq:latest
    container_name: nanomq
    ports:
      - "1883:1883"
      - "8080:8080"
      - "1884:1884"
    environment:
      NANOQ_LOG_LEVEL: info
    restart: always
    deploy:
      replicas: 1
    networks:
      iot:
        aliases:
          - nanomq

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.10.1
    environment:
      DATA_SOURCE_URI: "postgres:5432/postgresql?sslmode=disable"
      DATA_SOURCE_USER: "postgres"
      DATA_SOURCE_PASS: "cadri"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    ports:
      - "9187:9187"
    depends_on:
      - postgres-primary
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 500M
    networks:
      iot:
        aliases:
          - postgres

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: on-failure
    deploy:
      replicas: 1
    networks:
      iot:
        aliases:
          - prometheus

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    container_name: exporter
    hostname: exporter
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    ports:
      - 9100:9100
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      iot:
        aliases:
          - exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin_1
    restart: unless-stopped
    deploy:
      replicas: 1
    networks:
      iot:
        aliases:
          - grafana

  elasticsearch:
    image: elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: on-failure
    networks:
      iot:

  logstash:
    image: logstash:8.9.0
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./config/pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf
    environment:
      XPACK_MONITORING_ENABLED: "false"
      LOGSTASH_PORT: 5044
      LOGSTASH_INDEX: "test-index"
      ELASTIC_HOST: "elasticsearch:9200"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
    restart: on-failure
    networks:
      iot:

  kibana:
    image: kibana:8.15.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "elastic"
    depends_on:
      - elasticsearch
    restart: on-failure
    networks:
      iot:

  tsung:
    image: castelislogice/tsung:latest
    container_name: tsung
    depends_on:
      - nanomq
    ports:
      - "8081:8081"
    volumes:
      - ./tsung:/etc/tsung
    environment:
      - TSUNG_CONFIG=/etc/tsung/test.xml
    restart: unless-stopped
    networks:
      iot:
        aliases:
          - tsung

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      iot:
        aliases:
          - redis

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server_rule
    networks:
      iot:
        aliases:
          - nginx

networks:
  iot:
    driver: overlay
    attachable: true


volumes:
  pgadmin-data:
  es_data:
  elasticsearch_data:
  postgres-data-primary:
  postgres-data-replica1:
  citus-data:
  citus-worker1-data: